### ISSUE TITLE
NoClassDefFoundError when starting with 'mvn tomcat7:run'

### ISSUE THREAD

**Issue by jbellmann** [thymeleaf/thymeleafexamples-petclinic#3]
When try to build and run as mentioned in README.md I got the following error:

```
INFO  XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/business-config.xml]
INFO  XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/datasource-config.xml]
INFO  XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/tools-config.xml]
ERROR ContextLoader - Context initialization failed
java.lang.NoClassDefFoundError: org/springframework/beans/factory/NoUniqueBeanDefinitionException
    at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.7.0_15]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2451) ~[na:1.7.0_15]
    at java.lang.Class.getDeclaredMethods(Class.java:1810) ~[na:1.7.0_15]
    at org.springframework.core.type.StandardAnnotationMetadata.hasAnnotatedMethods(StandardAnnotationMetadata.java:159) ~[spring-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassUtils.isLiteConfigurationCandidate(ConfigurationClassUtils.java:106) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(ConfigurationClassUtils.java:87) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:257) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:227) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:623) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4791) [tomcat-embed-core-7.0.30.jar:7.0.30]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285) [tomcat-embed-core-7.0.30.jar:7.0.30]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.30.jar:7.0.30]
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [tomcat-embed-core-7.0.30.jar:7.0.30]
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [tomcat-embed-core-7.0.30.jar:7.0.30]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [na:1.7.0_15]
```

The output says there is an NoClassDefFoundError. But in spring-core-3.1.4.jar. But in the pom.xml version 3.2.2.RELEASE is specified. Right?

**Comment by jbellmann** [comment]
```
mvn dependency:tree > deps.txt
```

shows where the version 3.1.4.RELEASE comes from:

```
 +- javax.xml.bind:jaxb-api:jar:2.2.7:provided
[INFO] +- com.sun.xml.bind:jaxb-impl:jar:2.2.7-b53:provided
[INFO] +- org.thymeleaf:thymeleaf:jar:2.0.16:compile
[INFO] |  +- ognl:ognl:jar:3.0.5:compile
[INFO] |  \- org.javassist:javassist:jar:3.16.1-GA:compile
[INFO] +- org.thymeleaf:thymeleaf-spring3:jar:2.0.16:compile
[INFO] +- org.springframework.data:spring-data-jpa:jar:1.3.0.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.5.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:3.1.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-asm:jar:3.1.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:3.1.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-core:jar:3.1.4.RELEASE:compile
[INFO] +- org.springframework:spring-jdbc:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:3.2.2.RELEASE:compile
[INFO] |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] +- org.springframework:spring-webmvc:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.springframework:spring-expression:jar:3.2.2.RELEASE:compile
[INFO] |  \- org.springframework:spring-web:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-tx:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-orm:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-oxm:jar:3.2.2.RELEASE:compile
[INFO] +- org.springframework:spring-jms:jar:3.2.2.RELEASE:compile
[INFO] +- commons-dbcp:commons-dbcp:jar:1.4:runtime
[INFO] |  \- commons-pool:commons-pool:jar:1.5.4:runtime
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.2:runtime
[INFO] +- org.slf4j:slf4j-api:jar:1.7.2:runtime

```

Maybe this

```
            <!-- SPRING, SPRING, SPRINGITY SPRING -->
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>${spring-data-jpa.version}</version>
                <exclusions>
                    <exclusion>
                      <groupId>org.springframework</groupId>
                      <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

does not work with Maven 2.2.1.
Will try again with 3.0.5

**Comment by jbellmann** [comment]
Maven 3.0.5 marks the exclusion-element explicit as not valid:

```

[WARNING] Some problems were encountered while building the effective model for thymeleafexamples:petclinic:war:20130317
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for org.springframework.data:spring-data-jpa:jar with value '*' does not match a valid id pattern. @ line 129, column 26
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building petclinic 20130317
[INFO] ------------------------------------------------------------------------
[INFO] 
```

How did this work for you ????

But it resolves dependencies better. No 'NoClassDefFoundError' anymore when 'mvn clean install'.

**Comment by danielfernandez** [comment]
Actually, this is a problem with the original SpringSource application, as that part of the pom.xml was left completely unmodified from the original. See https://github.com/SpringSource/spring-petclinic/blob/master/pom.xml#L124

The `*` artifact ID specification seems to be a new feature in Maven 3, although not officially implemented, and it issues a warning. Something strange: http://jira.codehaus.org/browse/MNG-3832

So I've just changed the `pom.xml` file in order to explicitly specify versions for those transitive dependencies. Should be working for you now, even in Maven 2.
